post http://localhost:3333/events
Content-Type: application/json

{
    "title": "Novo evento 2",
    "details": null,
    "maximumAttendees": 1
}

###

post http://localhost:3333/events/05d68ecf-09e8-4fe2-85ec-48a88d695876/attendees
Content-Type: application/json

{
    "name": "Lucas Limeira",
    "email": "lucasdllimeira2@hotmail.com"
}